### ISSUE TITLE
Error VOERTUIGEN HERBENOEMEN

### ISSUE THREAD

**Issue by Rene-63** [LSS-Manager/lss-manager-v3#1008]
TypeError: Cannot read properties of undefined (reading 'replace')
    at HTMLAnchorElement.rename (https://proxy.lss-manager.de/v3/modules/lss-RenameFZ/renameFZ.user.js?uid=meldkamerspel214761:1898:31)
    at HTMLAnchorElement.dispatch (https://www.meldkamerspel.com/assets/application-9f32646d775c281dfd1b1b13c480bf5f.js:28:4312)
    at HTMLAnchorElement.g.handle (https://www.meldkamerspel.com/assets/application-9f32646d775c281dfd1b1b13c480bf5f.js:28:1017)

**Comment by jxn-30** [comment]
This happens, when LSSM has not detected a newly bought vehicle yet. A reload fixes this.
