### ISSUE TITLE
Rename vehicles

### ISSUE THREAD

**Issue by Rene-63** [LSS-Manager/lss-manager-v3#1121]
When renaming vehicles, the following error messages immediately occur. Rename vehicles in the monitoring center vehicles menu. Then some of the vehicles are renamed and then it crashes.
He stops at a DA-SIG. Presumably because the vehicle ID is not recognized yet??

TypeError: Cannot read properties of undefined (reading '0')
    at rename (https://v3.lss-manager.de/modules/lss-RenameFZ/renameFZ.user.js?uid=meldkamerspel214761:2040:52)
    at HTMLAnchorElement. (https://v3.lss-manager.de/modules/lss-RenameFZ/renameFZ.user.js?uid=meldkamerspel214761:2301:44)
    at HTMLAnchorElement.dispatch (https://www.meldkamerspel.com/assets/application-272e9c4df944103abd8d83dda3659d67.js:28:4312)
    at g.handle (https://www.meldkamerspel.com/assets/application-272e9c4df944103abd8d83dda3659d67.js:28:1017)

**Comment by Suchty112** [comment]
Should be fixed with this commit https://github.com/LSS-Manager/lss-manager-v3/commit/cf3f0a70bfab09c1ea6d3b02479374c30d81d88d
