### ISSUE TITLE
Problem bei Fahrzeug Umbennung

### ISSUE THREAD

**Issue by terfilter11** [LSS-Manager/lss-manager-v3#1171]
Hallo

Ich habe ein Problem beim Umbennen der Fahrzeuge, anbei die Log

TypeError
Cannot read properties of undefined (reading 'building')
TypeError: Cannot read properties of undefined (reading 'building')
    at rename (https://v3.lss-manager.de/modules/lss-RenameFZ/renameFZ.user.js:1244:50)
    at HTMLAnchorElement. (https://v3.lss-manager.de/modules/lss-RenameFZ/renameFZ.user.js:1514:44)
    at HTMLAnchorElement.dispatch (https://www.leitstellenspiel.de/assets/application-60bf040476b078e7267b2b5d5418315b.js:52:4392)
    at g.handle (https://www.leitstellenspiel.de/assets/application-60bf040476b078e7267b2b5d5418315b.js:52:1100)

MFG
terfilter11

**Comment by Suchty112** [comment]
Sollte hiermit behoben sein https://github.com/LSS-Manager/lss-manager-v3/commit/f5b9601053286fa6eceec4b4470d59c4950aa010
Es fehlte noch die Bergwacht in der v3 🙈 Gerne Rückmeldung

**Comment by terfilter11** [comment]
Hallo

Danke für die Meldung. Aber der Fehler besteht immer noch

*Cannot read properties of undefined (reading 'building')*

TypeError: Cannot read properties of undefined (reading 'building')
    at rename (https://v3.lss-manager.de/modules/lss-RenameFZ/renameFZ.user.js:1245:50)
    at HTMLAnchorElement.
(https://v3.lss-manager.de/modules/lss-RenameFZ/renameFZ.user.js:1515:44)
    at HTMLAnchorElement.dispatch
(https://www.leitstellenspiel.de/assets/application-60bf040476b078e7267b2b5d5418315b.js:52:4392)
    at g.handle
(https://www.leitstellenspiel.de/assets/application-60bf040476b078e7267b2b5d5418315b.js:52:1100)


Am Mo., 24. Juni 2024 um 10:06 Uhr schrieb Tobias ***@***.***

**Comment by Suchty112** [comment]
In was für einem GEbäude versuchst du den umzubennen?

**Comment by terfilter11** [comment]
Zuerst war der Fehler bei der Polizei und jetzt im Rettungsdienst

Am Mo., 24. Juni 2024 um 11:26 Uhr schrieb Tobias ***@***.***
