### ISSUE TITLE
TypeError Fahrzeuge umbenennen

### ISSUE THREAD

**Issue by 0800Jannis** [LSS-Manager/lss-manager-v3#695]
Ich hatte jetzt schon öfter folgenden Fehler:
 

> Status: Fehler bei der Generierung! Sollte dieser Fehler ein weiteres mal auftreten, bitte melde ihn. Bitte teile dann folgendes mit:

TypeError
Cannot read property 'building' of undefined
TypeError: Cannot read property 'building' of undefined
    at HTMLAnchorElement.rename (https://proxy.lss-manager.de/v3/modules/lss-RenameFZ/renameFZ.user.js?uid=leitstellenspiel586421:1825:50)
    at HTMLAnchorElement.dispatch (https://www.leitstellenspiel.de/assets/application-f22ad5cba7f3ea058355033542159004.js:27:4312)
    at HTMLAnchorElement.g.handle (https://www.leitstellenspiel.de/assets/application-f22ad5cba7f3ea058355033542159004.js:27:1017)

Ich habe Win 8 und nutze Opera

**Comment by Suchty112** [comment]
Das kommt meistens davon, dass das neue Auto/Gebäude noch nicht im Cache vom Browser/Spiel ist. da hilft nen reload oder auch mal STRG+F5 :)
